steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - goal-detector
  - --region=us-east1
  - --source=./goal-detector
  - --trigger-topic=messages
  - --runtime=python311
  - --gen2
  - --entry-point=subscribe
  - --service-account=vertex-ai-consumer-273@$PROJECT_ID.iam.gserviceaccount.com
  - --memory=8Gi
  - --cpu=8